### ISSUE TITLE
Please give an example

### ISSUE THREAD

**Issue by 4-alok** [illright/audiometa#2]
Give an example or some guide, 
very difficult for beginner.

**Comment by illright** [comment]
This library is very much alpha (not even published to Pub), but if you'd like to give it a try, this code sample might help:
```dart
void main() {
  var track = File('id3v23-test.mp3');
  extractTag(track.readAsBytesSync(), ID3.v1_1).frames.forEach((k, v) {
    for (var frame in v) {
      print('Frame ${frame.label}');
      if (frame is v1.TextFrame) {
        print('  Value: ${frame.text}');
        /*if (frame is v23.LangDescTextFrame) {
          print('  Language: ${frame.language}');
          print('  Description: ${frame.description}');
          print('  Encoding: ${frame.encoding}');
        }*/
      } else if (frame is v1.ByteFrame) {
        print('  Value: ${frame.value}');
        if (frame.label == 'Genre') {
          print('  Actual genre: ${v1.genreNames[frame.value]}');
        }
      }
    }
  });
}
```

**Comment by 4-alok** [comment]
Error: the name 'v1.TextFrame' isn't define, so it can't be used in as 'is' expression

**Comment by illright** [comment]
As I mentioned, this library is not yet ready for public usage, and I'm currently working on other projects. If you're only starting with Dart programming, I'd recommend taking a look at other libraries. If not, PRs are welcome.
